### ISSUE TITLE
Cant launch glacier kit. 

### ISSUE THREAD

**Issue by IKennyAgain** [atampy25/glacierkit#18]
When trying to launch Glacier Kit, it wont launch. 
It appears in Task Manager for a brief moment then closes itself. No visible windows appears on screen. 
Tried differnet compatabilities and run as admin.

**Comment by AnthonyFuller** [comment]
Anything related to GlacierKit in event viewer?

**Comment by IKennyAgain** [comment]
> Anything related to GlacierKit in event viewer?

No errors nor succeeded launches

**Comment by dafitius** [comment]
Can you check `%AppData%` to see if it contains a `app.glacierkit` folder?

**Comment by IKennyAgain** [comment]
> Can you check `%AppData%` to see if it contains a `app.glacierkit` folder?

it is in place, have a log file
[GlacierKit.log](https://github.com/user-attachments/files/17747537/GlacierKit.log)

**Comment by AnthonyFuller** [comment]
Have you uninstalled Edge at some point?

**Comment by IKennyAgain** [comment]
> The logs look normal _unfortunately_.
> 
> What @AnthonyFuller said is something to check. You need webview2 installed. It should be in `Control Panel -> Programs -> Microsoft Edge WebView2 Runtime`
> 
> Also make sure that antivirus isn't breaking things.
> 
> If none of this solve the issue you should try to find clues using [procmon](https://learn.microsoft.com/sysinternals/downloads/procmon)

OK so I didnt have Edge WebView 2, installed it and Glacier starts now. Thanks for help.
