### ISSUE TITLE
Add GitHub project and issue templates for better issue tracking

### ISSUE THREAD

**Issue by dafitius** [atampy25/glacierkit#4]
## Project Organization
To improve the management and tracking of bugs and feature requests, it would be nice to work with [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) and use a GitHub project board. These tools can help streamline issue submissions, assignments, and overall project organization.

#### Issue Templates:
- Bug Report template: Template for reporting bugs.
- Feature Request template: Template for submitting feature ideas.

#### GitHub Project Board:
- Organized columns (e.g., To Do, In Progress, Done) to track the progress of issues.
- Integration with labels (e.g., Bug, Enhancement)

**Comment by dafitius** [comment]
Can you set this up @atampy25 ?

**Comment by atampy25** [comment]
Done
